name: navigation
version: 0.0.1
publish_to: none
description: Navigation package.

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  home_screen:
    path: ../features/home_screen
  dishes_menu:
    path: ../features/dishes_menu
  order_history:
    path: ../features/order_history
  shopping_cart:
    path: ../features/shopping_cart
  settings:
    path: ../features/settings
  detailed_page:
    path: ../features/detailed_page
  sign_in_screen:
    path: ../features/sign_in_screen
  sign_up_screen:
    path: ../features/sign_up_screen
  main_page_screen:
    path: ../features/main_page_screen

  core:
    path: ../core
  domain: 
    path: ../domain
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.0
