name: home_screen
version: 0.0.1
publish_to: none
description: Home screen feature.

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_ui:
    path: ../../core_ui
  domain:
    path: ../../domain
  core:
    path: ../../core
  dishes_menu:
    path: ../dishes_menu
  order_history:
    path: ../order_history
  shopping_cart:
    path: ../shopping_cart
  settings:
    path: ../settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.0
