name: core
version: 0.0.1
publish_to: none
description: Project package that represents dependencies.

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.2
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.8.1
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.12
  google_sign_in: ^6.1.4
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
